# Generated by Django 5.2.1 on 2025-06-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=200)),
                ('Status', models.CharField(max_length=50)),
                ('DueDate', models.DateField()),
                ('CreatedAt', models.DateField(null=True)),
            ],
        ),
    ]
