# Generated by Django 5.2.1 on 2025-06-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField(max_length=3)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField(max_length=100)),
            ],
        ),
    ]
