# Generated by Django 5.2.1 on 2025-05-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Department', models.CharField(max_length=100)),
                ('Student_City', models.CharField(max_length=100)),
                ('Student_Age', models.IntegerField()),
            ],
        ),
    ]
