# Generated by Django 5.2.1 on 2025-05-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_Name', models.CharField(max_length=100)),
                ('Teacher_Subject', models.CharField(max_length=50)),
                ('Teacher_email', models.EmailField(max_length=254)),
                ('Teacher_phone', models.IntegerField(max_length=11)),
                ('Teacher_department', models.CharField(max_length=100)),
            ],
        ),
    ]
