# Generated by Django 5.2.3 on 2025-06-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskTitle', models.CharField(max_length=200)),
                ('TaskDescription', models.TextField(max_length=200)),
                ('TaskPriority', models.CharField(max_length=50)),
                ('TaskStatus', models.CharField(max_length=50)),
                ('TaskDueDate', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
