# Generated by Django 5.2.3 on 2025-06-28 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManagerApp', '0002_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='password',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='TaskDescription',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='TaskDueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='TaskPriority',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='TaskStatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='TaskTitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
