# Generated by Django 5.2.3 on 2025-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='media/images')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
