# Generated by Django 5.2.3 on 2025-06-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/recipes')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.IntegerField()),
                ('instructions', models.IntegerField()),
                ('creator', models.CharField(max_length=100)),
                ('description', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
