# Generated by Django 5.2.3 on 2025-06-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='creator',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/recipes'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
