# Generated by Django 5.2.3 on 2025-06-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookTitle', models.CharField(max_length=50)),
                ('BookAuthor', models.CharField(max_length=50)),
                ('BookCategory', models.CharField(max_length=100)),
                ('BookPublishDate', models.DateField()),
                ('BookDescription', models.TextField()),
            ],
        ),
    ]
