# Generated by Django 5.2.3 on 2025-06-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='BookCoverPhoto',
            field=models.ImageField(null=True, upload_to='Media/cover_photo'),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='BookAuthor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='BookCategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='BookDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='BookPublishDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='BookTitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
