# Generated by Django 5.2.1 on 2025-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_First_Name', models.CharField(max_length=100)),
                ('User_Last_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
