# Generated by Django 5.2.4 on 2025-07-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobProtalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobMode',
            new_name='JobModel',
        ),
    ]
