# Generated by Django 5.2.3 on 2025-06-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='TaskStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
