# Generated by Django 5.2.3 on 2025-06-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
