# Generated by Django 5.2.3 on 2025-06-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_crud_app', '0002_alter_customusermodel_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.TextField(max_length=200)),
                ('productPrice', models.PositiveIntegerField()),
                ('productImage', models.ImageField(upload_to='Midea/product')),
            ],
        ),
    ]
