# Generated by Django 5.2.3 on 2025-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='published_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
