# Generated by Django 5.2.3 on 2025-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=50)),
                ('StudentRoll', models.PositiveIntegerField()),
                ('StudentDepartment', models.CharField(max_length=100)),
                ('StudentImage', models.ImageField(upload_to='Student/img')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='todoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TodoTitle', models.CharField(max_length=50)),
                ('TodoDescription', models.CharField(max_length=100)),
                ('TodoStatus', models.CharField()),
                ('TodoDueDate', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
