# Generated by Django 5.2.3 on 2025-06-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecipeTitle', models.CharField(max_length=100)),
                ('RecipeDescription', models.CharField(max_length=200)),
                ('RecipeIngrefients', models.CharField(max_length=300)),
                ('RecipeInstructions', models.CharField(max_length=200)),
                ('RecipeImage', models.ImageField(upload_to='Recipe/cover')),
            ],
        ),
    ]
